//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supakulltracker.UserProvider {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserProvider.UserProviderSoap")]
    public interface UserProviderSoap {
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Find", ReplyAction="*")]
        Supakulltracker.UserProvider.FindResponse Find(Supakulltracker.UserProvider.FindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Find", ReplyAction="*")]
        System.Threading.Tasks.Task<Supakulltracker.UserProvider.FindResponse> FindAsync(Supakulltracker.UserProvider.FindRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Exist", ReplyAction="*")]
        Supakulltracker.UserProvider.ExistResponse Exist(Supakulltracker.UserProvider.ExistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Exist", ReplyAction="*")]
        System.Threading.Tasks.Task<Supakulltracker.UserProvider.ExistResponse> ExistAsync(Supakulltracker.UserProvider.ExistRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Find", Namespace="http://tempuri.org/", Order=0)]
        public Supakulltracker.UserProvider.FindRequestBody Body;
        
        public FindRequest() {
        }
        
        public FindRequest(Supakulltracker.UserProvider.FindRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        public FindRequestBody() {
        }
        
        public FindRequestBody(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindResponse", Namespace="http://tempuri.org/", Order=0)]
        public Supakulltracker.UserProvider.FindResponseBody Body;
        
        public FindResponse() {
        }
        
        public FindResponse(Supakulltracker.UserProvider.FindResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Supakulltracker.UserProvider.UserDTO FindResult;
        
        public FindResponseBody() {
        }
        
        public FindResponseBody(Supakulltracker.UserProvider.UserDTO FindResult) {
            this.FindResult = FindResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Exist", Namespace="http://tempuri.org/", Order=0)]
        public Supakulltracker.UserProvider.ExistRequestBody Body;
        
        public ExistRequest() {
        }
        
        public ExistRequest(Supakulltracker.UserProvider.ExistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        public ExistRequestBody() {
        }
        
        public ExistRequestBody(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExistResponse", Namespace="http://tempuri.org/", Order=0)]
        public Supakulltracker.UserProvider.ExistResponseBody Body;
        
        public ExistResponse() {
        }
        
        public ExistResponse(Supakulltracker.UserProvider.ExistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ExistResult;
        
        public ExistResponseBody() {
        }
        
        public ExistResponseBody(bool ExistResult) {
            this.ExistResult = ExistResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserProviderSoapChannel : Supakulltracker.UserProvider.UserProviderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserProviderSoapClient : System.ServiceModel.ClientBase<Supakulltracker.UserProvider.UserProviderSoap>, Supakulltracker.UserProvider.UserProviderSoap {
        
        public UserProviderSoapClient() {
        }
        
        public UserProviderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserProviderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProviderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProviderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Supakulltracker.UserProvider.FindResponse Supakulltracker.UserProvider.UserProviderSoap.Find(Supakulltracker.UserProvider.FindRequest request) {
            return base.Channel.Find(request);
        }
        
        public Supakulltracker.UserProvider.UserDTO Find(string userId) {
            Supakulltracker.UserProvider.FindRequest inValue = new Supakulltracker.UserProvider.FindRequest();
            inValue.Body = new Supakulltracker.UserProvider.FindRequestBody();
            inValue.Body.userId = userId;
            Supakulltracker.UserProvider.FindResponse retVal = ((Supakulltracker.UserProvider.UserProviderSoap)(this)).Find(inValue);
            return retVal.Body.FindResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Supakulltracker.UserProvider.FindResponse> Supakulltracker.UserProvider.UserProviderSoap.FindAsync(Supakulltracker.UserProvider.FindRequest request) {
            return base.Channel.FindAsync(request);
        }
        
        public System.Threading.Tasks.Task<Supakulltracker.UserProvider.FindResponse> FindAsync(string userId) {
            Supakulltracker.UserProvider.FindRequest inValue = new Supakulltracker.UserProvider.FindRequest();
            inValue.Body = new Supakulltracker.UserProvider.FindRequestBody();
            inValue.Body.userId = userId;
            return ((Supakulltracker.UserProvider.UserProviderSoap)(this)).FindAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Supakulltracker.UserProvider.ExistResponse Supakulltracker.UserProvider.UserProviderSoap.Exist(Supakulltracker.UserProvider.ExistRequest request) {
            return base.Channel.Exist(request);
        }
        
        public bool Exist(string userId) {
            Supakulltracker.UserProvider.ExistRequest inValue = new Supakulltracker.UserProvider.ExistRequest();
            inValue.Body = new Supakulltracker.UserProvider.ExistRequestBody();
            inValue.Body.userId = userId;
            Supakulltracker.UserProvider.ExistResponse retVal = ((Supakulltracker.UserProvider.UserProviderSoap)(this)).Exist(inValue);
            return retVal.Body.ExistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Supakulltracker.UserProvider.ExistResponse> Supakulltracker.UserProvider.UserProviderSoap.ExistAsync(Supakulltracker.UserProvider.ExistRequest request) {
            return base.Channel.ExistAsync(request);
        }
        
        public System.Threading.Tasks.Task<Supakulltracker.UserProvider.ExistResponse> ExistAsync(string userId) {
            Supakulltracker.UserProvider.ExistRequest inValue = new Supakulltracker.UserProvider.ExistRequest();
            inValue.Body = new Supakulltracker.UserProvider.ExistRequestBody();
            inValue.Body.userId = userId;
            return ((Supakulltracker.UserProvider.UserProviderSoap)(this)).ExistAsync(inValue);
        }
    }
}
