//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestServices.GetTrackerServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskMainDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TaskMainDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubtaskTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SummaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        private UnitTestServices.GetTrackerServices.Sources LinkToTrackerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstimationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestServices.GetTrackerServices.UserDTO[] AssignedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestServices.GetTrackerServices.TaskMainDTO TaskParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestServices.GetTrackerServices.TaskMainDTO[] MatchedTasksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TaskID {
            get {
                return this.TaskIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskIDField, value) != true)) {
                    this.TaskIDField = value;
                    this.RaisePropertyChanged("TaskID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SubtaskType {
            get {
                return this.SubtaskTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubtaskTypeField, value) != true)) {
                    this.SubtaskTypeField = value;
                    this.RaisePropertyChanged("SubtaskType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.PriorityField, value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Project {
            get {
                return this.ProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectField, value) != true)) {
                    this.ProjectField = value;
                    this.RaisePropertyChanged("Project");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedDateField, value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public UnitTestServices.GetTrackerServices.Sources LinkToTracker {
            get {
                return this.LinkToTrackerField;
            }
            set {
                if ((this.LinkToTrackerField.Equals(value) != true)) {
                    this.LinkToTrackerField = value;
                    this.RaisePropertyChanged("LinkToTracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Estimation {
            get {
                return this.EstimationField;
            }
            set {
                if ((object.ReferenceEquals(this.EstimationField, value) != true)) {
                    this.EstimationField = value;
                    this.RaisePropertyChanged("Estimation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string TargetVersion {
            get {
                return this.TargetVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetVersionField, value) != true)) {
                    this.TargetVersionField = value;
                    this.RaisePropertyChanged("TargetVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public UnitTestServices.GetTrackerServices.UserDTO[] Assigned {
            get {
                return this.AssignedField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedField, value) != true)) {
                    this.AssignedField = value;
                    this.RaisePropertyChanged("Assigned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public UnitTestServices.GetTrackerServices.TaskMainDTO TaskParent {
            get {
                return this.TaskParentField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskParentField, value) != true)) {
                    this.TaskParentField = value;
                    this.RaisePropertyChanged("TaskParent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public UnitTestServices.GetTrackerServices.TaskMainDTO[] MatchedTasks {
            get {
                return this.MatchedTasksField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchedTasksField, value) != true)) {
                    this.MatchedTasksField = value;
                    this.RaisePropertyChanged("MatchedTasks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sources", Namespace="http://tempuri.org/")]
    public enum Sources : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataBase = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Trello = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Excel = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GoogleSheets = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceAccountDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ServiceAccountDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ServiceAccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceAccountNameField;
        
        private UnitTestServices.GetTrackerServices.Sources SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestServices.GetTrackerServices.TemplateDTO[] MappingTemplatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestServices.GetTrackerServices.TokenDTO[] TokensField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ServiceAccountId {
            get {
                return this.ServiceAccountIdField;
            }
            set {
                if ((this.ServiceAccountIdField.Equals(value) != true)) {
                    this.ServiceAccountIdField = value;
                    this.RaisePropertyChanged("ServiceAccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceAccountName {
            get {
                return this.ServiceAccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceAccountNameField, value) != true)) {
                    this.ServiceAccountNameField = value;
                    this.RaisePropertyChanged("ServiceAccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public UnitTestServices.GetTrackerServices.Sources Source {
            get {
                return this.SourceField;
            }
            set {
                if ((this.SourceField.Equals(value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public UnitTestServices.GetTrackerServices.TemplateDTO[] MappingTemplates {
            get {
                return this.MappingTemplatesField;
            }
            set {
                if ((object.ReferenceEquals(this.MappingTemplatesField, value) != true)) {
                    this.MappingTemplatesField = value;
                    this.RaisePropertyChanged("MappingTemplates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public UnitTestServices.GetTrackerServices.TokenDTO[] Tokens {
            get {
                return this.TokensField;
            }
            set {
                if ((object.ReferenceEquals(this.TokensField, value) != true)) {
                    this.TokensField = value;
                    this.RaisePropertyChanged("Tokens");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemplateDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TemplateDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TemplateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestServices.GetTrackerServices.MappingForSerialization[] MappingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TemplateId {
            get {
                return this.TemplateIdField;
            }
            set {
                if ((this.TemplateIdField.Equals(value) != true)) {
                    this.TemplateIdField = value;
                    this.RaisePropertyChanged("TemplateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TemplateName {
            get {
                return this.TemplateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateNameField, value) != true)) {
                    this.TemplateNameField = value;
                    this.RaisePropertyChanged("TemplateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public UnitTestServices.GetTrackerServices.MappingForSerialization[] Mapping {
            get {
                return this.MappingField;
            }
            set {
                if ((object.ReferenceEquals(this.MappingField, value) != true)) {
                    this.MappingField = value;
                    this.RaisePropertyChanged("Mapping");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TokenDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TokeneIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokeneNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestServices.GetTrackerServices.TokenForSerialization[] TokensField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TokeneId {
            get {
                return this.TokeneIdField;
            }
            set {
                if ((this.TokeneIdField.Equals(value) != true)) {
                    this.TokeneIdField = value;
                    this.RaisePropertyChanged("TokeneId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TokeneName {
            get {
                return this.TokeneNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TokeneNameField, value) != true)) {
                    this.TokeneNameField = value;
                    this.RaisePropertyChanged("TokeneName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public UnitTestServices.GetTrackerServices.TokenForSerialization[] Tokens {
            get {
                return this.TokensField;
            }
            set {
                if ((object.ReferenceEquals(this.TokensField, value) != true)) {
                    this.TokensField = value;
                    this.RaisePropertyChanged("Tokens");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MappingForSerialization", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MappingForSerialization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenForSerialization", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TokenForSerialization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetTrackerServices.GetTrackerServicesSoap")]
    public interface GetTrackerServicesSoap {
        
        // CODEGEN: Generating message contract since element name GetAllTasksResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTasks", ReplyAction="*")]
        UnitTestServices.GetTrackerServices.GetAllTasksResponse GetAllTasks(UnitTestServices.GetTrackerServices.GetAllTasksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTasks", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestServices.GetTrackerServices.GetAllTasksResponse> GetAllTasksAsync(UnitTestServices.GetTrackerServices.GetAllTasksRequest request);
        
        // CODEGEN: Generating message contract since element name taskID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMatchedTasks", ReplyAction="*")]
        UnitTestServices.GetTrackerServices.GetMatchedTasksResponse GetMatchedTasks(UnitTestServices.GetTrackerServices.GetMatchedTasksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMatchedTasks", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestServices.GetTrackerServices.GetMatchedTasksResponse> GetMatchedTasksAsync(UnitTestServices.GetTrackerServices.GetMatchedTasksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        void Update();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateAsync();
        
        // CODEGEN: Generating message contract since element name GetAllUserAccountsByUserIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUserAccountsByUserID", ReplyAction="*")]
        UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDResponse GetAllUserAccountsByUserID(UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUserAccountsByUserID", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDResponse> GetAllUserAccountsByUserIDAsync(UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserAccountsByUserIDAndAccountIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserAccountsByUserIDAndAccountId", ReplyAction="*")]
        UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdResponse GetUserAccountsByUserIDAndAccountId(UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserAccountsByUserIDAndAccountId", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdResponse> GetUserAccountsByUserIDAndAccountIdAsync(UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTasksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTasks", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestServices.GetTrackerServices.GetAllTasksRequestBody Body;
        
        public GetAllTasksRequest() {
        }
        
        public GetAllTasksRequest(UnitTestServices.GetTrackerServices.GetAllTasksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTasksRequestBody {
        
        public GetAllTasksRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTasksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTasksResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestServices.GetTrackerServices.GetAllTasksResponseBody Body;
        
        public GetAllTasksResponse() {
        }
        
        public GetAllTasksResponse(UnitTestServices.GetTrackerServices.GetAllTasksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTasksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UnitTestServices.GetTrackerServices.TaskMainDTO[] GetAllTasksResult;
        
        public GetAllTasksResponseBody() {
        }
        
        public GetAllTasksResponseBody(UnitTestServices.GetTrackerServices.TaskMainDTO[] GetAllTasksResult) {
            this.GetAllTasksResult = GetAllTasksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMatchedTasksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMatchedTasks", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestServices.GetTrackerServices.GetMatchedTasksRequestBody Body;
        
        public GetMatchedTasksRequest() {
        }
        
        public GetMatchedTasksRequest(UnitTestServices.GetTrackerServices.GetMatchedTasksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMatchedTasksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string taskID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public UnitTestServices.GetTrackerServices.Sources linkToTracker;
        
        public GetMatchedTasksRequestBody() {
        }
        
        public GetMatchedTasksRequestBody(string taskID, UnitTestServices.GetTrackerServices.Sources linkToTracker) {
            this.taskID = taskID;
            this.linkToTracker = linkToTracker;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMatchedTasksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMatchedTasksResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestServices.GetTrackerServices.GetMatchedTasksResponseBody Body;
        
        public GetMatchedTasksResponse() {
        }
        
        public GetMatchedTasksResponse(UnitTestServices.GetTrackerServices.GetMatchedTasksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMatchedTasksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UnitTestServices.GetTrackerServices.TaskMainDTO[] GetMatchedTasksResult;
        
        public GetMatchedTasksResponseBody() {
        }
        
        public GetMatchedTasksResponseBody(UnitTestServices.GetTrackerServices.TaskMainDTO[] GetMatchedTasksResult) {
            this.GetMatchedTasksResult = GetMatchedTasksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUserAccountsByUserIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUserAccountsByUserID", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDRequestBody Body;
        
        public GetAllUserAccountsByUserIDRequest() {
        }
        
        public GetAllUserAccountsByUserIDRequest(UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUserAccountsByUserIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        public GetAllUserAccountsByUserIDRequestBody() {
        }
        
        public GetAllUserAccountsByUserIDRequestBody(int userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUserAccountsByUserIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUserAccountsByUserIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDResponseBody Body;
        
        public GetAllUserAccountsByUserIDResponse() {
        }
        
        public GetAllUserAccountsByUserIDResponse(UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUserAccountsByUserIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UnitTestServices.GetTrackerServices.ServiceAccountDTO[] GetAllUserAccountsByUserIDResult;
        
        public GetAllUserAccountsByUserIDResponseBody() {
        }
        
        public GetAllUserAccountsByUserIDResponseBody(UnitTestServices.GetTrackerServices.ServiceAccountDTO[] GetAllUserAccountsByUserIDResult) {
            this.GetAllUserAccountsByUserIDResult = GetAllUserAccountsByUserIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAccountsByUserIDAndAccountIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserAccountsByUserIDAndAccountId", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdRequestBody Body;
        
        public GetUserAccountsByUserIDAndAccountIdRequest() {
        }
        
        public GetUserAccountsByUserIDAndAccountIdRequest(UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserAccountsByUserIDAndAccountIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int seviceAccountId;
        
        public GetUserAccountsByUserIDAndAccountIdRequestBody() {
        }
        
        public GetUserAccountsByUserIDAndAccountIdRequestBody(int userId, int seviceAccountId) {
            this.userId = userId;
            this.seviceAccountId = seviceAccountId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAccountsByUserIDAndAccountIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserAccountsByUserIDAndAccountIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdResponseBody Body;
        
        public GetUserAccountsByUserIDAndAccountIdResponse() {
        }
        
        public GetUserAccountsByUserIDAndAccountIdResponse(UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserAccountsByUserIDAndAccountIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UnitTestServices.GetTrackerServices.ServiceAccountDTO GetUserAccountsByUserIDAndAccountIdResult;
        
        public GetUserAccountsByUserIDAndAccountIdResponseBody() {
        }
        
        public GetUserAccountsByUserIDAndAccountIdResponseBody(UnitTestServices.GetTrackerServices.ServiceAccountDTO GetUserAccountsByUserIDAndAccountIdResult) {
            this.GetUserAccountsByUserIDAndAccountIdResult = GetUserAccountsByUserIDAndAccountIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetTrackerServicesSoapChannel : UnitTestServices.GetTrackerServices.GetTrackerServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTrackerServicesSoapClient : System.ServiceModel.ClientBase<UnitTestServices.GetTrackerServices.GetTrackerServicesSoap>, UnitTestServices.GetTrackerServices.GetTrackerServicesSoap {
        
        public GetTrackerServicesSoapClient() {
        }
        
        public GetTrackerServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetTrackerServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetTrackerServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetTrackerServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestServices.GetTrackerServices.GetAllTasksResponse UnitTestServices.GetTrackerServices.GetTrackerServicesSoap.GetAllTasks(UnitTestServices.GetTrackerServices.GetAllTasksRequest request) {
            return base.Channel.GetAllTasks(request);
        }
        
        public UnitTestServices.GetTrackerServices.TaskMainDTO[] GetAllTasks() {
            UnitTestServices.GetTrackerServices.GetAllTasksRequest inValue = new UnitTestServices.GetTrackerServices.GetAllTasksRequest();
            inValue.Body = new UnitTestServices.GetTrackerServices.GetAllTasksRequestBody();
            UnitTestServices.GetTrackerServices.GetAllTasksResponse retVal = ((UnitTestServices.GetTrackerServices.GetTrackerServicesSoap)(this)).GetAllTasks(inValue);
            return retVal.Body.GetAllTasksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestServices.GetTrackerServices.GetAllTasksResponse> UnitTestServices.GetTrackerServices.GetTrackerServicesSoap.GetAllTasksAsync(UnitTestServices.GetTrackerServices.GetAllTasksRequest request) {
            return base.Channel.GetAllTasksAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestServices.GetTrackerServices.GetAllTasksResponse> GetAllTasksAsync() {
            UnitTestServices.GetTrackerServices.GetAllTasksRequest inValue = new UnitTestServices.GetTrackerServices.GetAllTasksRequest();
            inValue.Body = new UnitTestServices.GetTrackerServices.GetAllTasksRequestBody();
            return ((UnitTestServices.GetTrackerServices.GetTrackerServicesSoap)(this)).GetAllTasksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestServices.GetTrackerServices.GetMatchedTasksResponse UnitTestServices.GetTrackerServices.GetTrackerServicesSoap.GetMatchedTasks(UnitTestServices.GetTrackerServices.GetMatchedTasksRequest request) {
            return base.Channel.GetMatchedTasks(request);
        }
        
        public UnitTestServices.GetTrackerServices.TaskMainDTO[] GetMatchedTasks(string taskID, UnitTestServices.GetTrackerServices.Sources linkToTracker) {
            UnitTestServices.GetTrackerServices.GetMatchedTasksRequest inValue = new UnitTestServices.GetTrackerServices.GetMatchedTasksRequest();
            inValue.Body = new UnitTestServices.GetTrackerServices.GetMatchedTasksRequestBody();
            inValue.Body.taskID = taskID;
            inValue.Body.linkToTracker = linkToTracker;
            UnitTestServices.GetTrackerServices.GetMatchedTasksResponse retVal = ((UnitTestServices.GetTrackerServices.GetTrackerServicesSoap)(this)).GetMatchedTasks(inValue);
            return retVal.Body.GetMatchedTasksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestServices.GetTrackerServices.GetMatchedTasksResponse> UnitTestServices.GetTrackerServices.GetTrackerServicesSoap.GetMatchedTasksAsync(UnitTestServices.GetTrackerServices.GetMatchedTasksRequest request) {
            return base.Channel.GetMatchedTasksAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestServices.GetTrackerServices.GetMatchedTasksResponse> GetMatchedTasksAsync(string taskID, UnitTestServices.GetTrackerServices.Sources linkToTracker) {
            UnitTestServices.GetTrackerServices.GetMatchedTasksRequest inValue = new UnitTestServices.GetTrackerServices.GetMatchedTasksRequest();
            inValue.Body = new UnitTestServices.GetTrackerServices.GetMatchedTasksRequestBody();
            inValue.Body.taskID = taskID;
            inValue.Body.linkToTracker = linkToTracker;
            return ((UnitTestServices.GetTrackerServices.GetTrackerServicesSoap)(this)).GetMatchedTasksAsync(inValue);
        }
        
        public void Update() {
            base.Channel.Update();
        }
        
        public System.Threading.Tasks.Task UpdateAsync() {
            return base.Channel.UpdateAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDResponse UnitTestServices.GetTrackerServices.GetTrackerServicesSoap.GetAllUserAccountsByUserID(UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDRequest request) {
            return base.Channel.GetAllUserAccountsByUserID(request);
        }
        
        public UnitTestServices.GetTrackerServices.ServiceAccountDTO[] GetAllUserAccountsByUserID(int userId) {
            UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDRequest inValue = new UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDRequest();
            inValue.Body = new UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDRequestBody();
            inValue.Body.userId = userId;
            UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDResponse retVal = ((UnitTestServices.GetTrackerServices.GetTrackerServicesSoap)(this)).GetAllUserAccountsByUserID(inValue);
            return retVal.Body.GetAllUserAccountsByUserIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDResponse> UnitTestServices.GetTrackerServices.GetTrackerServicesSoap.GetAllUserAccountsByUserIDAsync(UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDRequest request) {
            return base.Channel.GetAllUserAccountsByUserIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDResponse> GetAllUserAccountsByUserIDAsync(int userId) {
            UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDRequest inValue = new UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDRequest();
            inValue.Body = new UnitTestServices.GetTrackerServices.GetAllUserAccountsByUserIDRequestBody();
            inValue.Body.userId = userId;
            return ((UnitTestServices.GetTrackerServices.GetTrackerServicesSoap)(this)).GetAllUserAccountsByUserIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdResponse UnitTestServices.GetTrackerServices.GetTrackerServicesSoap.GetUserAccountsByUserIDAndAccountId(UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdRequest request) {
            return base.Channel.GetUserAccountsByUserIDAndAccountId(request);
        }
        
        public UnitTestServices.GetTrackerServices.ServiceAccountDTO GetUserAccountsByUserIDAndAccountId(int userId, int seviceAccountId) {
            UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdRequest inValue = new UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdRequest();
            inValue.Body = new UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.seviceAccountId = seviceAccountId;
            UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdResponse retVal = ((UnitTestServices.GetTrackerServices.GetTrackerServicesSoap)(this)).GetUserAccountsByUserIDAndAccountId(inValue);
            return retVal.Body.GetUserAccountsByUserIDAndAccountIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdResponse> UnitTestServices.GetTrackerServices.GetTrackerServicesSoap.GetUserAccountsByUserIDAndAccountIdAsync(UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdRequest request) {
            return base.Channel.GetUserAccountsByUserIDAndAccountIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdResponse> GetUserAccountsByUserIDAndAccountIdAsync(int userId, int seviceAccountId) {
            UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdRequest inValue = new UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdRequest();
            inValue.Body = new UnitTestServices.GetTrackerServices.GetUserAccountsByUserIDAndAccountIdRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.seviceAccountId = seviceAccountId;
            return ((UnitTestServices.GetTrackerServices.GetTrackerServicesSoap)(this)).GetUserAccountsByUserIDAndAccountIdAsync(inValue);
        }
    }
}
