AlTER TABLE TASKMAIN ADD "TK_SOURCE" VARCHAR2(20 BYTE) ;

DROP INDEX TASKMAIN_INDEX_ID_TRACKER;

 CREATE UNIQUE INDEX "DOFER"."TASKMAIN_INDEX_ID_TRACKER" ON "DOFER"."TASKMAIN" ("TK_TASKID", "TK_SOURCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

commit;