//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supakulltracker.IssueService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskMainDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TaskMainDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubtaskTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SummaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        private Supakulltracker.IssueService.Sources LinkToTrackerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstimationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Supakulltracker.IssueService.UserDTO[] AssignedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Supakulltracker.IssueService.TaskMainDTO TaskParentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TaskID {
            get {
                return this.TaskIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskIDField, value) != true)) {
                    this.TaskIDField = value;
                    this.RaisePropertyChanged("TaskID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SubtaskType {
            get {
                return this.SubtaskTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubtaskTypeField, value) != true)) {
                    this.SubtaskTypeField = value;
                    this.RaisePropertyChanged("SubtaskType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.PriorityField, value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Project {
            get {
                return this.ProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectField, value) != true)) {
                    this.ProjectField = value;
                    this.RaisePropertyChanged("Project");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedDateField, value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public Supakulltracker.IssueService.Sources LinkToTracker {
            get {
                return this.LinkToTrackerField;
            }
            set {
                if ((this.LinkToTrackerField.Equals(value) != true)) {
                    this.LinkToTrackerField = value;
                    this.RaisePropertyChanged("LinkToTracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Estimation {
            get {
                return this.EstimationField;
            }
            set {
                if ((object.ReferenceEquals(this.EstimationField, value) != true)) {
                    this.EstimationField = value;
                    this.RaisePropertyChanged("Estimation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string TargetVersion {
            get {
                return this.TargetVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetVersionField, value) != true)) {
                    this.TargetVersionField = value;
                    this.RaisePropertyChanged("TargetVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public Supakulltracker.IssueService.UserDTO[] Assigned {
            get {
                return this.AssignedField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedField, value) != true)) {
                    this.AssignedField = value;
                    this.RaisePropertyChanged("Assigned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public Supakulltracker.IssueService.TaskMainDTO TaskParent {
            get {
                return this.TaskParentField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskParentField, value) != true)) {
                    this.TaskParentField = value;
                    this.RaisePropertyChanged("TaskParent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sources", Namespace="http://tempuri.org/")]
    public enum Sources : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataBase = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Trello = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Excel = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GoogleSheets = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceAccountDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ServiceAccountDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ServiceAccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceAccountNameField;
        
        private Supakulltracker.IssueService.Sources SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Supakulltracker.IssueService.TemplateDTO[] MappingTemplatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Supakulltracker.IssueService.TokenDTO[] TokensField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ServiceAccountId {
            get {
                return this.ServiceAccountIdField;
            }
            set {
                if ((this.ServiceAccountIdField.Equals(value) != true)) {
                    this.ServiceAccountIdField = value;
                    this.RaisePropertyChanged("ServiceAccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceAccountName {
            get {
                return this.ServiceAccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceAccountNameField, value) != true)) {
                    this.ServiceAccountNameField = value;
                    this.RaisePropertyChanged("ServiceAccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Supakulltracker.IssueService.Sources Source {
            get {
                return this.SourceField;
            }
            set {
                if ((this.SourceField.Equals(value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Supakulltracker.IssueService.TemplateDTO[] MappingTemplates {
            get {
                return this.MappingTemplatesField;
            }
            set {
                if ((object.ReferenceEquals(this.MappingTemplatesField, value) != true)) {
                    this.MappingTemplatesField = value;
                    this.RaisePropertyChanged("MappingTemplates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Supakulltracker.IssueService.TokenDTO[] Tokens {
            get {
                return this.TokensField;
            }
            set {
                if ((object.ReferenceEquals(this.TokensField, value) != true)) {
                    this.TokensField = value;
                    this.RaisePropertyChanged("Tokens");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemplateDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TemplateDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TemplateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Supakulltracker.IssueService.MappingForSerialization[] MappingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TemplateId {
            get {
                return this.TemplateIdField;
            }
            set {
                if ((this.TemplateIdField.Equals(value) != true)) {
                    this.TemplateIdField = value;
                    this.RaisePropertyChanged("TemplateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TemplateName {
            get {
                return this.TemplateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateNameField, value) != true)) {
                    this.TemplateNameField = value;
                    this.RaisePropertyChanged("TemplateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Supakulltracker.IssueService.MappingForSerialization[] Mapping {
            get {
                return this.MappingField;
            }
            set {
                if ((object.ReferenceEquals(this.MappingField, value) != true)) {
                    this.MappingField = value;
                    this.RaisePropertyChanged("Mapping");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TokenDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TokenIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Supakulltracker.IssueService.TokenForSerialization[] TokensField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TokenId {
            get {
                return this.TokenIdField;
            }
            set {
                if ((this.TokenIdField.Equals(value) != true)) {
                    this.TokenIdField = value;
                    this.RaisePropertyChanged("TokenId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TokenName {
            get {
                return this.TokenNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenNameField, value) != true)) {
                    this.TokenNameField = value;
                    this.RaisePropertyChanged("TokenName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Supakulltracker.IssueService.TokenForSerialization[] Tokens {
            get {
                return this.TokensField;
            }
            set {
                if ((object.ReferenceEquals(this.TokensField, value) != true)) {
                    this.TokensField = value;
                    this.RaisePropertyChanged("Tokens");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MappingForSerialization", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MappingForSerialization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenForSerialization", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TokenForSerialization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IssueService.GetTrackerServicesSoap")]
    public interface GetTrackerServicesSoap {
        
        // CODEGEN: Generating message contract since element name GetAllTasksResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTasks", ReplyAction="*")]
        Supakulltracker.IssueService.GetAllTasksResponse GetAllTasks(Supakulltracker.IssueService.GetAllTasksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTasks", ReplyAction="*")]
        System.Threading.Tasks.Task<Supakulltracker.IssueService.GetAllTasksResponse> GetAllTasksAsync(Supakulltracker.IssueService.GetAllTasksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        void Update();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateAsync();
        
        // CODEGEN: Generating message contract since element name GetAllUserAccountsByUserIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUserAccountsByUserID", ReplyAction="*")]
        Supakulltracker.IssueService.GetAllUserAccountsByUserIDResponse GetAllUserAccountsByUserID(Supakulltracker.IssueService.GetAllUserAccountsByUserIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUserAccountsByUserID", ReplyAction="*")]
        System.Threading.Tasks.Task<Supakulltracker.IssueService.GetAllUserAccountsByUserIDResponse> GetAllUserAccountsByUserIDAsync(Supakulltracker.IssueService.GetAllUserAccountsByUserIDRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserAccountsByUserIDAndAccountIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserAccountsByUserIDAndAccountId", ReplyAction="*")]
        Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdResponse GetUserAccountsByUserIDAndAccountId(Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserAccountsByUserIDAndAccountId", ReplyAction="*")]
        System.Threading.Tasks.Task<Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdResponse> GetUserAccountsByUserIDAndAccountIdAsync(Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTasksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTasks", Namespace="http://tempuri.org/", Order=0)]
        public Supakulltracker.IssueService.GetAllTasksRequestBody Body;
        
        public GetAllTasksRequest() {
        }
        
        public GetAllTasksRequest(Supakulltracker.IssueService.GetAllTasksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTasksRequestBody {
        
        public GetAllTasksRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTasksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTasksResponse", Namespace="http://tempuri.org/", Order=0)]
        public Supakulltracker.IssueService.GetAllTasksResponseBody Body;
        
        public GetAllTasksResponse() {
        }
        
        public GetAllTasksResponse(Supakulltracker.IssueService.GetAllTasksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTasksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Supakulltracker.IssueService.TaskMainDTO[] GetAllTasksResult;
        
        public GetAllTasksResponseBody() {
        }
        
        public GetAllTasksResponseBody(Supakulltracker.IssueService.TaskMainDTO[] GetAllTasksResult) {
            this.GetAllTasksResult = GetAllTasksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUserAccountsByUserIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUserAccountsByUserID", Namespace="http://tempuri.org/", Order=0)]
        public Supakulltracker.IssueService.GetAllUserAccountsByUserIDRequestBody Body;
        
        public GetAllUserAccountsByUserIDRequest() {
        }
        
        public GetAllUserAccountsByUserIDRequest(Supakulltracker.IssueService.GetAllUserAccountsByUserIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUserAccountsByUserIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long userId;
        
        public GetAllUserAccountsByUserIDRequestBody() {
        }
        
        public GetAllUserAccountsByUserIDRequestBody(long userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUserAccountsByUserIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUserAccountsByUserIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Supakulltracker.IssueService.GetAllUserAccountsByUserIDResponseBody Body;
        
        public GetAllUserAccountsByUserIDResponse() {
        }
        
        public GetAllUserAccountsByUserIDResponse(Supakulltracker.IssueService.GetAllUserAccountsByUserIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUserAccountsByUserIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Supakulltracker.IssueService.ServiceAccountDTO[] GetAllUserAccountsByUserIDResult;
        
        public GetAllUserAccountsByUserIDResponseBody() {
        }
        
        public GetAllUserAccountsByUserIDResponseBody(Supakulltracker.IssueService.ServiceAccountDTO[] GetAllUserAccountsByUserIDResult) {
            this.GetAllUserAccountsByUserIDResult = GetAllUserAccountsByUserIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAccountsByUserIDAndAccountIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserAccountsByUserIDAndAccountId", Namespace="http://tempuri.org/", Order=0)]
        public Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdRequestBody Body;
        
        public GetUserAccountsByUserIDAndAccountIdRequest() {
        }
        
        public GetUserAccountsByUserIDAndAccountIdRequest(Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserAccountsByUserIDAndAccountIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int seviceAccountId;
        
        public GetUserAccountsByUserIDAndAccountIdRequestBody() {
        }
        
        public GetUserAccountsByUserIDAndAccountIdRequestBody(long userId, int seviceAccountId) {
            this.userId = userId;
            this.seviceAccountId = seviceAccountId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAccountsByUserIDAndAccountIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserAccountsByUserIDAndAccountIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdResponseBody Body;
        
        public GetUserAccountsByUserIDAndAccountIdResponse() {
        }
        
        public GetUserAccountsByUserIDAndAccountIdResponse(Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserAccountsByUserIDAndAccountIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Supakulltracker.IssueService.ServiceAccountDTO GetUserAccountsByUserIDAndAccountIdResult;
        
        public GetUserAccountsByUserIDAndAccountIdResponseBody() {
        }
        
        public GetUserAccountsByUserIDAndAccountIdResponseBody(Supakulltracker.IssueService.ServiceAccountDTO GetUserAccountsByUserIDAndAccountIdResult) {
            this.GetUserAccountsByUserIDAndAccountIdResult = GetUserAccountsByUserIDAndAccountIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetTrackerServicesSoapChannel : Supakulltracker.IssueService.GetTrackerServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTrackerServicesSoapClient : System.ServiceModel.ClientBase<Supakulltracker.IssueService.GetTrackerServicesSoap>, Supakulltracker.IssueService.GetTrackerServicesSoap {
        
        public GetTrackerServicesSoapClient() {
        }
        
        public GetTrackerServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetTrackerServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetTrackerServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetTrackerServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Supakulltracker.IssueService.GetAllTasksResponse Supakulltracker.IssueService.GetTrackerServicesSoap.GetAllTasks(Supakulltracker.IssueService.GetAllTasksRequest request) {
            return base.Channel.GetAllTasks(request);
        }
        
        public Supakulltracker.IssueService.TaskMainDTO[] GetAllTasks() {
            Supakulltracker.IssueService.GetAllTasksRequest inValue = new Supakulltracker.IssueService.GetAllTasksRequest();
            inValue.Body = new Supakulltracker.IssueService.GetAllTasksRequestBody();
            Supakulltracker.IssueService.GetAllTasksResponse retVal = ((Supakulltracker.IssueService.GetTrackerServicesSoap)(this)).GetAllTasks(inValue);
            return retVal.Body.GetAllTasksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Supakulltracker.IssueService.GetAllTasksResponse> Supakulltracker.IssueService.GetTrackerServicesSoap.GetAllTasksAsync(Supakulltracker.IssueService.GetAllTasksRequest request) {
            return base.Channel.GetAllTasksAsync(request);
        }
        
        public System.Threading.Tasks.Task<Supakulltracker.IssueService.GetAllTasksResponse> GetAllTasksAsync() {
            Supakulltracker.IssueService.GetAllTasksRequest inValue = new Supakulltracker.IssueService.GetAllTasksRequest();
            inValue.Body = new Supakulltracker.IssueService.GetAllTasksRequestBody();
            return ((Supakulltracker.IssueService.GetTrackerServicesSoap)(this)).GetAllTasksAsync(inValue);
        }
        
        public void Update() {
            base.Channel.Update();
        }
        
        public System.Threading.Tasks.Task UpdateAsync() {
            return base.Channel.UpdateAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Supakulltracker.IssueService.GetAllUserAccountsByUserIDResponse Supakulltracker.IssueService.GetTrackerServicesSoap.GetAllUserAccountsByUserID(Supakulltracker.IssueService.GetAllUserAccountsByUserIDRequest request) {
            return base.Channel.GetAllUserAccountsByUserID(request);
        }
        
        public Supakulltracker.IssueService.ServiceAccountDTO[] GetAllUserAccountsByUserID(long userId) {
            Supakulltracker.IssueService.GetAllUserAccountsByUserIDRequest inValue = new Supakulltracker.IssueService.GetAllUserAccountsByUserIDRequest();
            inValue.Body = new Supakulltracker.IssueService.GetAllUserAccountsByUserIDRequestBody();
            inValue.Body.userId = userId;
            Supakulltracker.IssueService.GetAllUserAccountsByUserIDResponse retVal = ((Supakulltracker.IssueService.GetTrackerServicesSoap)(this)).GetAllUserAccountsByUserID(inValue);
            return retVal.Body.GetAllUserAccountsByUserIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Supakulltracker.IssueService.GetAllUserAccountsByUserIDResponse> Supakulltracker.IssueService.GetTrackerServicesSoap.GetAllUserAccountsByUserIDAsync(Supakulltracker.IssueService.GetAllUserAccountsByUserIDRequest request) {
            return base.Channel.GetAllUserAccountsByUserIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Supakulltracker.IssueService.GetAllUserAccountsByUserIDResponse> GetAllUserAccountsByUserIDAsync(long userId) {
            Supakulltracker.IssueService.GetAllUserAccountsByUserIDRequest inValue = new Supakulltracker.IssueService.GetAllUserAccountsByUserIDRequest();
            inValue.Body = new Supakulltracker.IssueService.GetAllUserAccountsByUserIDRequestBody();
            inValue.Body.userId = userId;
            return ((Supakulltracker.IssueService.GetTrackerServicesSoap)(this)).GetAllUserAccountsByUserIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdResponse Supakulltracker.IssueService.GetTrackerServicesSoap.GetUserAccountsByUserIDAndAccountId(Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdRequest request) {
            return base.Channel.GetUserAccountsByUserIDAndAccountId(request);
        }
        
        public Supakulltracker.IssueService.ServiceAccountDTO GetUserAccountsByUserIDAndAccountId(long userId, int seviceAccountId) {
            Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdRequest inValue = new Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdRequest();
            inValue.Body = new Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.seviceAccountId = seviceAccountId;
            Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdResponse retVal = ((Supakulltracker.IssueService.GetTrackerServicesSoap)(this)).GetUserAccountsByUserIDAndAccountId(inValue);
            return retVal.Body.GetUserAccountsByUserIDAndAccountIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdResponse> Supakulltracker.IssueService.GetTrackerServicesSoap.GetUserAccountsByUserIDAndAccountIdAsync(Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdRequest request) {
            return base.Channel.GetUserAccountsByUserIDAndAccountIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdResponse> GetUserAccountsByUserIDAndAccountIdAsync(long userId, int seviceAccountId) {
            Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdRequest inValue = new Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdRequest();
            inValue.Body = new Supakulltracker.IssueService.GetUserAccountsByUserIDAndAccountIdRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.seviceAccountId = seviceAccountId;
            return ((Supakulltracker.IssueService.GetTrackerServicesSoap)(this)).GetUserAccountsByUserIDAndAccountIdAsync(inValue);
        }
    }
}
